apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL25lY2RlbW8=
  AZP_POOL: dWJ1bnR1LWFnZW50LWluLWNsdXN0ZXI=
  AZP_TOKEN: TnVSVG5YS0N1TVNPR1NDNmtEUjN6d0JvV25hT2kwcWJxWHpDRG04bzFOTFFXeEozekNOS0pRUUo5OUJMQUNBQUFBQWtlNnNnQUFBU0FaRE8xVkhn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 2 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: nec2005/dockeragent:amd64
        env:
        - name: AZP_URL
          valueFrom:
            secretKeyRef:
              name: pipeline-auth
              key: AZP_URL
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-auth
              key: AZP_TOKEN
        - name: AZP_POOL
          valueFrom:
            secretKeyRef:
              name: pipeline-auth
              key: AZP_POOL
        - name: AZP_AGENT_NAME
          value: "Agent Deployment-Linux"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock