apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL2hvdXNzZW1kZWxsYWk= # https://dev.azure.com/necdemo
  AZP_POOL: bGludXgtY29udGFpbmVycy1ha3M= # ubuntu-deployment-cluster
  AZP_TOKEN: <YOUR_PAT_TOKEN>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: devopsagent
  labels:
    app: azdevops-agent
spec:
  replicas: 2 #here is the configuration for the actual agent always running
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: nec2005/dockeragent:1.0.0
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock